"""empty message

Revision ID: 9e424fb9b8cb
Revises: 
Create Date: 2020-06-15 17:56:07.168310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e424fb9b8cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('article_id', sa.String(length=20), nullable=False),
    sa.Column('article_title', sa.String(length=100), nullable=False),
    sa.Column('article_text', sa.Text(), nullable=True),
    sa.Column('article_summary', sa.String(length=255), nullable=True),
    sa.Column('article_read_cnt', sa.Integer(), nullable=True),
    sa.Column('article_sc', sa.Integer(), nullable=True),
    sa.Column('article_pl', sa.Integer(), nullable=True),
    sa.Column('article_date', sa.DateTime(), nullable=True),
    sa.Column('article_url', sa.Text(), nullable=True),
    sa.Column('article_type', sa.String(length=10), nullable=True),
    sa.Column('article_author', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.String(length=20), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('comment_date', sa.DateTime(), nullable=True),
    sa.Column('comment_name', sa.String(length=30), nullable=True),
    sa.Column('comment_support', sa.Integer(), nullable=True),
    sa.Column('comment_oppose', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('commparam',
    sa.Column('param_name', sa.String(length=10), nullable=False),
    sa.Column('param_value', sa.Integer(), nullable=True),
    sa.Column('param_text', sa.String(length=100), nullable=True),
    sa.Column('param_stat', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('param_name')
    )
    op.create_table('fiction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiction_name', sa.String(), nullable=True),
    sa.Column('fiction_id', sa.String(), nullable=True),
    sa.Column('fiction_real_url', sa.String(), nullable=True),
    sa.Column('fiction_img', sa.String(), nullable=True),
    sa.Column('fiction_author', sa.String(), nullable=True),
    sa.Column('fiction_comment', sa.String(), nullable=True),
    sa.Column('update', sa.String(), nullable=True),
    sa.Column('new_content', sa.String(), nullable=True),
    sa.Column('new_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiction_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiction_url', sa.String(length=255), nullable=True),
    sa.Column('fiction_content', sa.Text(), nullable=True),
    sa.Column('fiction_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiction_lst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiction_name', sa.String(length=255), nullable=True),
    sa.Column('fiction_id', sa.String(length=255), nullable=True),
    sa.Column('fiction_lst_url', sa.String(length=255), nullable=True),
    sa.Column('fiction_lst_name', sa.String(length=255), nullable=True),
    sa.Column('fiction_real_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('task_id', sa.String(length=20), nullable=False),
    sa.Column('task_name', sa.String(length=50), nullable=False),
    sa.Column('start_dt', sa.String(length=16), nullable=True),
    sa.Column('next_dt', sa.String(length=16), nullable=True),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('stat', sa.String(length=10), nullable=True),
    sa.Column('remind', sa.String(length=10), nullable=True),
    sa.Column('article_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('emails', sa.String(length=200), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=True),
    sa.Column('nickname', sa.String(length=40), nullable=True),
    sa.Column('sex', sa.String(length=4), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('last_login_tm', sa.DateTime(), nullable=True),
    sa.Column('user_crt_dt', sa.DateTime(), nullable=True),
    sa.Column('attention_cnt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('task')
    op.drop_table('fiction_lst')
    op.drop_table('fiction_content')
    op.drop_table('fiction')
    op.drop_table('commparam')
    op.drop_table('comment')
    op.drop_table('article')
    # ### end Alembic commands ###
